# Generated by Django 4.2.19 on 2025-03-03 21:21

import apps.portfolio_chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.portfolio_chat.models.message_file_path),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'New Message'), ('file', 'New File'), ('hiring', 'Hiring Update'), ('system', 'System Notification')], max_length=20),
        ),
    ]
