# Generated by Django 4.2.19 on 2025-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
