# Generated by Django 4.2.19 on 2025-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringrequest',
            old_name='budget',
            new_name='price',
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('priced', 'Priced'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('priced', 'Priced'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('priced', 'Priced'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
