# Generated by Django 4.2.19 on 2025-02-28 21:48

from django.db import migrations
from django.utils import timezone

def generate_ticket_number(apps, schema_editor):
    HiringRequest = apps.get_model('hiring', 'HiringRequest')
    
    # Get all requests without ticket numbers
    requests = HiringRequest.objects.filter(ticket_number__isnull=True)
    
    for request in requests:
        # Generate ticket number: HR-YYMM-XXXX
        prefix = 'HR'
        date_part = request.created_at.strftime('%y%m')
        
        # Find the last ticket number for this month
        last_ticket = HiringRequest.objects.filter(
            ticket_number__startswith=f'{prefix}-{date_part}'
        ).order_by('-ticket_number').first()
        
        if last_ticket:
            last_number = int(last_ticket.ticket_number.split('-')[-1])
            new_number = str(last_number + 1).zfill(4)
        else:
            new_number = '0001'
        
        request.ticket_number = f'{prefix}-{date_part}-{new_number}'
        request.save()

def reverse_ticket_numbers(apps, schema_editor):
    HiringRequest = apps.get_model('hiring', 'HiringRequest')
    HiringRequest.objects.update(ticket_number=None)

class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_rename_budget_hiringrequest_price_and_more'),
    ]

    operations = [
        migrations.RunPython(
            generate_ticket_number,
            reverse_ticket_numbers
        ),
    ]
