# Generated by Django 4.2.19 on 2025-03-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_generate_ticket_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiringrequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_set_price', 'Can set price for request'), ('can_process_payment', 'Can process payment for request')]},
        ),
        migrations.RemoveField(
            model_name='hiringrequest',
            name='price',
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
