# Generated by Django 4.2.19 on 2025-03-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
